### ISSUE TITLE
Android app?

### ISSUE THREAD

**Issue by bootofood** [PierrickP/n26#26]
Hello,

Do you plan to release this as an open source N26 app?
Or, are you aware of such a project?

**Comment by PierrickP** [comment]
Hello bootofood,

This project is just an **un-official** node.js module for interacting with n26 API like the official webapp or mobile.

I released an [n26 cli](https://github.com/PierrickP/number26-cli) (with few functionnalities and some unfinished things).
With this module, we can imagine to develop an electron app !

For mac, you can also check https://github.com/kiliankoe/alfred_n26
