### ISSUE TITLE
Recognize corresponding PT and AA transactions

### ISSUE THREAD

**Issue by Philipp91** [PierrickP/n26#28]
When I use my MasterCard, I usually get a transaction of type `AA`, which is converted into a `PT` transaction after a couple of days. Sometimes, the `amount` changes a bit (if it's a foreign currency) and sometimes the `merchantName or `merchantCity` changes a bit (truncated, spaces trimmed, all-caps, etc.).

When a new `PT` transaction shows up, is there a _reliable_ way to tell which one the previously present `AA` transaction was? The old API used to have a `linkId` that was the same for both transactions, but the `smrt` API fillls that field with the regular `id` value and that one changes.

**Comment by PierrickP** [comment]
Hi,
Sorry i have no idea.
As this module is totally unofficial & i'm not affiliate with n26, you should ask them directly.
Cordially
