### ISSUE TITLE
Web push notification

### ISSUE THREAD

**Issue by Meemaw** [PierrickP/n26#43]
Hello. Great work! 

I was wondering if you could implement web push notifications as they are for sms and mail. It would just send a POST with params to provided url.

**Comment by PierrickP** [comment]
Hello,
Thank you. What do you mean by push notification ? 
Notification like 
![image](https://user-images.githubusercontent.com/1214544/30151897-a06a2f56-93b1-11e7-9c50-4599b5075cfa.png)
?
I don't work for N26, I have no idea how to get this thing on my module

**Comment by Philipp91** [comment]
As far as I know, the N26 API does not expose any information in a "push" kind of way. Therefore, PierrickP's library cannot do anything for you. I assume that the official apps use other mechanisms (e.g. Firebase) to trigger a regular fetch/sync when new information is available.

If you're interested in getting information as soon as possible, you can intercept this trigger on Android phones if you install a `NotificationListenerService` and look for the notifications that the N26 app displays. Whenever one of those appears, you can trigger a fetch through your own server (and possibly the `n26` library). This works reasonably fast (1-5 seconds) and doesn't consume much battery, as the device is awake and actively online at that time anyway.

**Comment by Meemaw** [comment]
I am building a web app and would like to sync it with my N26 purchases.

**Comment by Philipp91** [comment]
Then the best you can do is sync regularly, e.g. with a cronjob. But don't do it too often so that N26 servers don't get flooded. Their API is not officially supported and using it with an automated system through a library like `n26` is not what the API is intended for -- it's just meant to serve the apps and web interface of N26 itself.
