### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by cldt-fr** [PierrickP/n26#52]
Hello, 

I have a bug when I fetch N26 Api, can you help me please ?

[Click-here for screenshot](https://gyazo.com/abea066f578a904348fec411999da022)

Thank you in advance,

Clément

**Comment by Philipp91** [comment]
This is a node.js module, which means it doesn't necessarily work in browsers. And it seems that it doesn't work in browsers that enforce CORS.

**Comment by cldt-fr** [comment]
Thank you
